package junitpractice;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

//public class Junit1111 {


		
		// Generated by Selenium IDE
		import org.junit.Test;
		import org.junit.Before;
		import org.junit.After;
		import static org.junit.Assert.*;
		import static org.hamcrest.CoreMatchers.is;
		import static org.hamcrest.core.IsNot.not;
		import org.openqa.selenium.By;
		import org.openqa.selenium.WebDriver;
		import org.openqa.selenium.firefox.FirefoxDriver;
		import org.openqa.selenium.chrome.ChromeDriver;
		import org.openqa.selenium.remote.RemoteWebDriver;
		import org.openqa.selenium.remote.DesiredCapabilities;
		import org.openqa.selenium.Dimension;
		import org.openqa.selenium.WebElement;
		import org.openqa.selenium.interactions.Actions;
		import org.openqa.selenium.support.ui.ExpectedConditions;
		import org.openqa.selenium.support.ui.WebDriverWait;
		import org.openqa.selenium.JavascriptExecutor;
		import org.openqa.selenium.Alert;
		import org.openqa.selenium.Keys;
		import java.util.*;
		import java.net.MalformedURLException;
		import java.net.URL;
		@SuppressWarnings("unused")
		public class Testfileaddingtodriver {
		  private WebDriver driver;
		  private Map<String, Object> vars;
		  JavascriptExecutor js;
		  @Before
		  public void setUp() {
		    driver = new ChromeDriver();
		    js = (JavascriptExecutor) driver;
		    vars = new HashMap<String, Object>();
		  }
		  @After
		  public void tearDown() {
		    driver.quit();
		  }
		  @SuppressWarnings("deprecation")
		@Test
		  public void asa1() {
		    driver.get("https://www.selenium.dev/");
		    driver.manage().window().setSize(new Dimension(1552, 832));
		    driver.findElement(By.id("navbarDropdown")).click();
		    driver.findElement(By.linkText("Ecosystem")).click();
		    {
		      WebElement element = driver.findElement(By.cssSelector(".nav-item:nth-child(4) span"));
		      Actions builder = new Actions(driver);
		      builder.moveToElement(element).perform();
		    }
		    {
		      WebElement element = driver.findElement(By.tagName("body"));
		      Actions builder = new Actions(driver);
		      builder.moveToElement(element, 0, 0).perform();
		    }
		    driver.findElement(By.cssSelector(".nav-item:nth-child(3) span")).click();
		    driver.findElement(By.cssSelector(".nav-item:nth-child(5) span")).click();
		    js.executeScript("window.scrollTo(0,0)");
		    driver.findElement(By.cssSelector(".nav-item:nth-child(6) span")).click();
		    driver.findElement(By.cssSelector(".nav-item:nth-child(7) span")).click();
		    driver.findElement(By.cssSelector("#m-blog2015 > span")).click();
		    driver.findElement(By.cssSelector(".DocSearch-Button-Placeholder")).click();
		    driver.findElement(By.id("docsearch-input")).sendKeys("java");
		    driver.findElement(By.id("docsearch-input")).sendKeys(Keys.ENTER);
		    {
		      WebElement element = driver.findElement(By.cssSelector(".DocSearch"));
		      Actions builder = new Actions(driver);
		      builder.moveToElement(element).perform();
		    }
		    {
		      WebElement element = driver.findElement(By.tagName("body"));
		      Actions builder = new Actions(driver);
		      builder.moveToElement(element, 0, 0).perform();
		    }
		    js.executeScript("window.scrollTo(0,575.2000122070312)");
		    //driver.quit();
		   /* driver.findElement(By.cssSelector(".<td>-content")).click();
		    driver.findElement(By.linkText("See a sample prompt")).click();
		    assertThat(driver.switchTo().alert().getText(), is("What is your tool of choice?"));
		    driver.switchTo().alert().dismiss();
		    driver.findElement(By.cssSelector(".selenium-button")).click();*/
		  }
		

		//

}

